// Bundled placeholder pixel art sprites for all plants.
// IDs 1-60: spring plants. IDs 61-120: summer placeholders (same art, pending Replicate generation).
// IDs 121-180: autumn placeholders. IDs 181-240: winter placeholders.
// Used as fallback when pixel_sprite_url from Supabase is NULL.
// Replace with Replicate-generated sprites when API token is available.

const SPRITE_MAP: Record<number, any> = {
  1: require('../../assets/sprites/plant_1.png'),
  2: require('../../assets/sprites/plant_2.png'),
  3: require('../../assets/sprites/plant_3.png'),
  4: require('../../assets/sprites/plant_4.png'),
  5: require('../../assets/sprites/plant_5.png'),
  6: require('../../assets/sprites/plant_6.png'),
  7: require('../../assets/sprites/plant_7.png'),
  8: require('../../assets/sprites/plant_8.png'),
  9: require('../../assets/sprites/plant_9.png'),
  10: require('../../assets/sprites/plant_10.png'),
  11: require('../../assets/sprites/plant_11.png'),
  12: require('../../assets/sprites/plant_12.png'),
  13: require('../../assets/sprites/plant_13.png'),
  14: require('../../assets/sprites/plant_14.png'),
  15: require('../../assets/sprites/plant_15.png'),
  16: require('../../assets/sprites/plant_16.png'),
  17: require('../../assets/sprites/plant_17.png'),
  18: require('../../assets/sprites/plant_18.png'),
  19: require('../../assets/sprites/plant_19.png'),
  20: require('../../assets/sprites/plant_20.png'),
  21: require('../../assets/sprites/plant_21.png'),
  22: require('../../assets/sprites/plant_22.png'),
  23: require('../../assets/sprites/plant_23.png'),
  24: require('../../assets/sprites/plant_24.png'),
  25: require('../../assets/sprites/plant_25.png'),
  26: require('../../assets/sprites/plant_26.png'),
  27: require('../../assets/sprites/plant_27.png'),
  28: require('../../assets/sprites/plant_28.png'),
  29: require('../../assets/sprites/plant_29.png'),
  30: require('../../assets/sprites/plant_30.png'),
  31: require('../../assets/sprites/plant_31.png'),
  32: require('../../assets/sprites/plant_32.png'),
  33: require('../../assets/sprites/plant_33.png'),
  34: require('../../assets/sprites/plant_34.png'),
  35: require('../../assets/sprites/plant_35.png'),
  36: require('../../assets/sprites/plant_36.png'),
  37: require('../../assets/sprites/plant_37.png'),
  38: require('../../assets/sprites/plant_38.png'),
  39: require('../../assets/sprites/plant_39.png'),
  40: require('../../assets/sprites/plant_40.png'),
  41: require('../../assets/sprites/plant_41.png'),
  42: require('../../assets/sprites/plant_42.png'),
  43: require('../../assets/sprites/plant_43.png'),
  44: require('../../assets/sprites/plant_44.png'),
  45: require('../../assets/sprites/plant_45.png'),
  46: require('../../assets/sprites/plant_46.png'),
  47: require('../../assets/sprites/plant_47.png'),
  48: require('../../assets/sprites/plant_48.png'),
  49: require('../../assets/sprites/plant_49.png'),
  50: require('../../assets/sprites/plant_50.png'),
  51: require('../../assets/sprites/plant_51.png'),
  52: require('../../assets/sprites/plant_52.png'),
  53: require('../../assets/sprites/plant_53.png'),
  54: require('../../assets/sprites/plant_54.png'),
  55: require('../../assets/sprites/plant_55.png'),
  56: require('../../assets/sprites/plant_56.png'),
  57: require('../../assets/sprites/plant_57.png'),
  58: require('../../assets/sprites/plant_58.png'),
  59: require('../../assets/sprites/plant_59.png'),
  60: require('../../assets/sprites/plant_60.png'),
  // Summer placeholders (IDs 61-120) — pending Replicate-generated art
  61: require('../../assets/sprites/plant_61.png'),
  62: require('../../assets/sprites/plant_62.png'),
  63: require('../../assets/sprites/plant_63.png'),
  64: require('../../assets/sprites/plant_64.png'),
  65: require('../../assets/sprites/plant_65.png'),
  66: require('../../assets/sprites/plant_66.png'),
  67: require('../../assets/sprites/plant_67.png'),
  68: require('../../assets/sprites/plant_68.png'),
  69: require('../../assets/sprites/plant_69.png'),
  70: require('../../assets/sprites/plant_70.png'),
  71: require('../../assets/sprites/plant_71.png'),
  72: require('../../assets/sprites/plant_72.png'),
  73: require('../../assets/sprites/plant_73.png'),
  74: require('../../assets/sprites/plant_74.png'),
  75: require('../../assets/sprites/plant_75.png'),
  76: require('../../assets/sprites/plant_76.png'),
  77: require('../../assets/sprites/plant_77.png'),
  78: require('../../assets/sprites/plant_78.png'),
  79: require('../../assets/sprites/plant_79.png'),
  80: require('../../assets/sprites/plant_80.png'),
  81: require('../../assets/sprites/plant_81.png'),
  82: require('../../assets/sprites/plant_82.png'),
  83: require('../../assets/sprites/plant_83.png'),
  84: require('../../assets/sprites/plant_84.png'),
  85: require('../../assets/sprites/plant_85.png'),
  86: require('../../assets/sprites/plant_86.png'),
  87: require('../../assets/sprites/plant_87.png'),
  88: require('../../assets/sprites/plant_88.png'),
  89: require('../../assets/sprites/plant_89.png'),
  90: require('../../assets/sprites/plant_90.png'),
  91: require('../../assets/sprites/plant_91.png'),
  92: require('../../assets/sprites/plant_92.png'),
  93: require('../../assets/sprites/plant_93.png'),
  94: require('../../assets/sprites/plant_94.png'),
  95: require('../../assets/sprites/plant_95.png'),
  96: require('../../assets/sprites/plant_96.png'),
  97: require('../../assets/sprites/plant_97.png'),
  98: require('../../assets/sprites/plant_98.png'),
  99: require('../../assets/sprites/plant_99.png'),
  100: require('../../assets/sprites/plant_100.png'),
  101: require('../../assets/sprites/plant_101.png'),
  102: require('../../assets/sprites/plant_102.png'),
  103: require('../../assets/sprites/plant_103.png'),
  104: require('../../assets/sprites/plant_104.png'),
  105: require('../../assets/sprites/plant_105.png'),
  106: require('../../assets/sprites/plant_106.png'),
  107: require('../../assets/sprites/plant_107.png'),
  108: require('../../assets/sprites/plant_108.png'),
  109: require('../../assets/sprites/plant_109.png'),
  110: require('../../assets/sprites/plant_110.png'),
  111: require('../../assets/sprites/plant_111.png'),
  112: require('../../assets/sprites/plant_112.png'),
  113: require('../../assets/sprites/plant_113.png'),
  114: require('../../assets/sprites/plant_114.png'),
  115: require('../../assets/sprites/plant_115.png'),
  116: require('../../assets/sprites/plant_116.png'),
  117: require('../../assets/sprites/plant_117.png'),
  118: require('../../assets/sprites/plant_118.png'),
  119: require('../../assets/sprites/plant_119.png'),
  120: require('../../assets/sprites/plant_120.png'),
};

/**
 * Get the bundled placeholder sprite for a plant by ID.
 * Returns the require() source for <Image source={...} />.
 * Returns undefined if no sprite exists for the given ID.
 */
export function getPlantSprite(plantId: number): any | undefined {
  return SPRITE_MAP[plantId];
}
