#!/bin/bash
# Pre-submission screenshot consistency check
# Run before App Store review submission to verify screenshots match current UI
#
# Usage: bash scripts/screenshot-consistency-check.sh

set -e
FAIL=0

echo "=== Screenshot Consistency Check ==="
echo ""

# 1. Check screenshot sequence does NOT reference hidden tabs
echo "[1] Hidden tab guard:"
HIDDEN_TABS="footprint discover herbarium map social profile"
SEQ_FILE="src/hooks/useScreenshotSequence.ts"
for TAB in $HIDDEN_TABS; do
  if grep -q "(tabs)/${TAB}" "$SEQ_FILE" 2>/dev/null; then
    echo "  ERROR: hidden tab '$TAB' found in screenshot sequence!"
    FAIL=1
  fi
done
if [ $FAIL -eq 0 ]; then
  echo "  OK: no hidden tabs in screenshot sequence"
fi

# 2. Check screenshot signal count matches across pipeline
echo ""
echo "[2] Pipeline count consistency:"
SEQ_COUNT=$(grep -c "await signalAndWait" "$SEQ_FILE" 2>/dev/null || echo 0)
COMPOSE_COUNT=$(grep -c "input:" scripts/screenshot-compose.mjs 2>/dev/null || echo 0)
CI_COUNT=$(grep -c 'capture_signal "' .github/workflows/screenshot-build.yml 2>/dev/null || echo 0)
echo "  Sequence signals: $SEQ_COUNT"
echo "  Compose entries:  $COMPOSE_COUNT"
echo "  CI captures:      $CI_COUNT"
if [ "$SEQ_COUNT" -ne "$COMPOSE_COUNT" ] || [ "$SEQ_COUNT" -ne "$CI_COUNT" ]; then
  echo "  ERROR: counts do not match across pipeline files!"
  FAIL=1
else
  echo "  OK: all $SEQ_COUNT screens consistent"
fi

# 3. Check screenshot files exist
echo ""
echo "[3] Screenshot files:"
EXPECTED_FILES=$(grep -oP "e2e/current/\S+\.png" .github/workflows/screenshot-build.yml 2>/dev/null | sed 's/"//g')
for F in $EXPECTED_FILES; do
  if [ -f "$F" ]; then
    echo "  OK: $F exists"
  else
    echo "  WARN: $F missing (will be generated by screenshot workflow)"
  fi
done

# 4. App version check
echo ""
echo "[4] App version:"
APP_VERSION=$(node -e "console.log(require('./app.json').expo.version)" 2>/dev/null)
BUILD_NUMBER=$(node -e "console.log(require('./app.json').expo.ios.buildNumber)" 2>/dev/null)
echo "  version: $APP_VERSION (build $BUILD_NUMBER)"

echo ""
echo "=== Result ==="
if [ $FAIL -eq 0 ]; then
  echo "PASS: All checks passed"
else
  echo "FAIL: Issues found — fix before ASC submission"
fi
exit $FAIL
